@echo off
chcp 65001 >nul
:: BridgeBox-adapted Flowseal "general (ALT13).bat".
:: Auto-generated by bridgebox.zapret.strategy_adapt - selected the TCP
:: 80+443 and QUIC profiles from the original, discarded the rest.
:: Layout: winws.exe + WinDivert + *.bin live in vendor/zapret/ (parent of this file).
:: Runs winws in the foreground (no "start") so BridgeBox can track the process.
:: Domains come only from lists\list-jackbox.txt (--hostlist).

setlocal
cd /d "%~dp0.."
set "BIN=%cd%\"
set "LISTS=%cd%\lists\"
set "HOSTLIST=%LISTS%list-jackbox.txt"

if exist "%BIN%winws.exe" goto :bb_check_hostlist
echo [BridgeBox] winws.exe not found in "%BIN%"
exit /b 1

:bb_check_hostlist
if exist "%HOSTLIST%" goto :bb_run
echo [BridgeBox] hostlist not found: "%HOSTLIST%"
exit /b 1

:bb_run

"%BIN%winws.exe" ^
  --wf-tcp=80,443,38203 ^
  --wf-udp=443 ^
  --filter-tcp=80,443,38203 ^
  --hostlist="%HOSTLIST%" ^
  --dpi-desync=fake,hostfakesplit ^
  --dpi-desync-fooling=ts ^
  --dpi-desync-hostfakesplit-mod=host=mail.ru,altorder=1 ^
  --dpi-desync-repeats=5 ^
  --dpi-desync-fake-tls="%BIN%tls_clienthello_sochi_park.bin" ^
  --dpi-desync-fake-tls="%BIN%stun2.bin" ^
  --dpi-desync-fake-http="%BIN%tls_clienthello_sochi_park.bin" ^
  --new ^
  --filter-udp=443 ^
  --hostlist="%HOSTLIST%" ^
  --dpi-desync=fake ^
  --dpi-desync-repeats=11 ^
  --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin"

endlocal
:: BridgeBox-stamp 1.10.2 5f857c4157fe3a112d4b40c93cdb64036600ddeba7e49248c90856af3f25c996
