"""File integrity detection.

Replaces install_security.py's ACL hardening: the folder now stays writable,
and the app instead notices and reports when its own files change. The finding
behind both is the same - the install folder inherits write access for any
local account - and this module's whole job is catching that after the fact
rather than preventing it, which the module docstring is explicit about.
"""
import sys
from pathlib import Path

import pytest

from bridgebox import integrity


def _tree(tmp_path: Path) -> Path:
    root = tmp_path / "BridgeBox"
    (root / "zapret" / "strategies").mkdir(parents=True)
    (root / "backend" / "bridgebox").mkdir(parents=True)
    (root / "zapret" / "winws.exe").write_bytes(b"MZ...")
    (root / "zapret" / "strategies" / "General.bat").write_text("@echo off\n")
    (root / "backend" / "bridgebox" / "desktop.py").write_text("# app\n")
    (root / "launcher.py").write_text("# launcher\n")
    (root / "config.yaml").write_text("server:\n  port: 8443\n")
    return root


# ---- what gets watched ---------------------------------------------------


def test_config_and_certs_are_not_watched(tmp_path: Path):
    """These change during ordinary use - a settings edit, a generated key -
    and watching them would fire the banner on every normal session."""
    root = _tree(tmp_path)
    (root / "logs").mkdir()
    (root / "logs" / "bridgebox.log").write_text("...")
    (root / "certs").mkdir()
    (root / "certs" / "localhost.pem").write_text("...")

    files = {p.as_posix() for p in integrity.watched_files(root)}

    assert "config.yaml" not in files
    assert not any(f.startswith("logs/") for f in files)
    assert not any(f.startswith("certs/") for f in files)


def test_the_executable_surface_is_watched(tmp_path: Path):
    root = _tree(tmp_path)

    files = {p.as_posix() for p in integrity.watched_files(root)}

    assert "zapret/winws.exe" in files
    assert "zapret/strategies/General.bat" in files
    assert "backend/bridgebox/desktop.py" in files
    assert "launcher.py" in files


def test_pycache_and_venvs_are_never_watched(tmp_path: Path):
    """Regenerated by the interpreter / package manager on every run - watching
    them would make the banner fire from nothing but starting the app."""
    root = _tree(tmp_path)
    (root / "backend" / "bridgebox" / "__pycache__").mkdir()
    (root / "backend" / "bridgebox" / "__pycache__" / "desktop.cpython-312.pyc").write_bytes(b"x")

    files = {p.as_posix() for p in integrity.watched_files(root)}

    assert not any("__pycache__" in f for f in files)


def test_the_manifest_is_reproducible(tmp_path: Path):
    """Two runs over the same tree must produce byte-identical manifests - a
    manifest that reorders itself looks changed when nothing changed."""
    root = _tree(tmp_path)

    assert integrity.build_manifest(root) == integrity.build_manifest(root)


# ---- verification ---------------------------------------------------------


def test_a_fresh_install_has_no_baseline_and_is_not_reported_as_tampered(tmp_path: Path):
    root = _tree(tmp_path)

    report = integrity.verify(root)

    assert report.baseline_missing is True
    assert report.verified is False  # "unknown" is not "fine"


def test_an_untouched_tree_verifies(tmp_path: Path):
    root = _tree(tmp_path)
    integrity.write_manifest(root)

    report = integrity.verify(root)

    assert report.verified is True
    assert report.total == 0


def test_an_edited_file_is_reported_as_changed(tmp_path: Path):
    """The scenario from the report: a strategy .bat that no longer matches
    what shipped."""
    root = _tree(tmp_path)
    integrity.write_manifest(root)

    (root / "zapret" / "strategies" / "General.bat").write_text("@echo off\nrem tampered\n")

    report = integrity.verify(root)

    assert report.verified is False
    assert "zapret/strategies/General.bat" in report.changed
    assert report.missing == []
    assert report.added == []


def test_a_deleted_watched_file_is_reported_as_missing(tmp_path: Path):
    root = _tree(tmp_path)
    integrity.write_manifest(root)

    (root / "launcher.py").unlink()

    report = integrity.verify(root)

    assert "launcher.py" in report.missing


def test_a_new_watched_file_is_reported_as_added(tmp_path: Path):
    root = _tree(tmp_path)
    integrity.write_manifest(root)

    (root / "zapret" / "strategies" / "Sneaky.bat").write_text("@echo off\n")

    report = integrity.verify(root)

    assert "zapret/strategies/Sneaky.bat" in report.added


def test_an_edit_outside_the_watched_set_is_invisible(tmp_path: Path):
    """config.yaml changes on every settings save. If that showed up here the
    banner would fire on the most ordinary action in the app."""
    root = _tree(tmp_path)
    integrity.write_manifest(root)

    (root / "config.yaml").write_text("server:\n  port: 9999\n")

    report = integrity.verify(root)

    assert report.verified is True


def test_a_runtime_stderr_log_inside_the_frozen_bundle_is_not_tampering(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """PyInstaller creates this diagnostic file on a clean portable launch."""
    root = _tree(tmp_path)
    monkeypatch.setattr(
        integrity,
        "WATCHED_GLOBS",
        ("bridgebox.exe", "_internal/**/*") + integrity._ZAPRET_GLOBS,
    )
    integrity.write_manifest(root)

    stderr_log = root / "_internal" / "log" / "launcher-stderr.log"
    stderr_log.parent.mkdir(parents=True)
    stderr_log.write_text("startup diagnostic\n", encoding="utf-8")

    assert integrity.verify(root).verified is True


def test_ensure_baseline_writes_one_on_first_run_and_reports_fine(tmp_path: Path):
    root = _tree(tmp_path)

    first = integrity.ensure_baseline(root)

    assert first.verified is True
    assert integrity.manifest_path(root).exists()


def test_ensure_baseline_does_not_overwrite_an_existing_one(tmp_path: Path):
    """The trust-on-first-use step must only run ONCE - re-baselining on every
    launch would mean tampering between two launches is silently absorbed."""
    root = _tree(tmp_path)
    integrity.ensure_baseline(root)
    (root / "launcher.py").write_text("# tampered after the baseline\n")

    report = integrity.ensure_baseline(root)

    assert report.verified is False
    assert "launcher.py" in report.changed


def test_a_manifest_from_the_future_is_not_trusted_blindly(tmp_path: Path):
    """Not a real version skew scenario yet - MANIFEST_VERSION is 1 - but
    read_manifest must not crash on a shape it does not recognise, since a
    malformed or hand-edited manifest is exactly the case worth being careful
    about."""
    root = _tree(tmp_path)
    integrity.manifest_path(root).write_text('{"not": "a manifest"}', encoding="utf-8")

    assert integrity.read_manifest(root) is None


def test_verify_never_raises_on_a_corrupt_manifest(tmp_path: Path):
    root = _tree(tmp_path)
    integrity.manifest_path(root).write_text("not even json", encoding="utf-8")

    report = integrity.verify(root)

    assert report.baseline_missing is True  # an unreadable manifest reads as none


def test_report_serialises_for_the_bridge(tmp_path: Path):
    root = _tree(tmp_path)
    integrity.write_manifest(root)
    (root / "launcher.py").unlink()

    payload = integrity.verify(root).as_dict()

    assert set(payload) == {
        "verified", "baselineMissing", "changed", "missing", "added", "total", "error",
    }
    assert payload["total"] == 1


def test_the_manifest_is_not_pretty_printed(tmp_path: Path):
    """One line, no indent - the previous multi-line, one-hash-per-line
    format was itself an invitation to hand-edit a single entry to match a
    tampered file."""
    root = _tree(tmp_path)
    integrity.write_manifest(root)

    assert integrity.manifest_path(root).read_text(encoding="utf-8").count("\n") == 0


def test_the_baseline_is_hidden_only_in_a_frozen_build(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """Source checkouts want baseline.json visible - a developer poking
    through their own repo is not who this hides it from. Only a portable
    build's release folder gets the Windows hidden+system attributes."""
    root = _tree(tmp_path)
    calls: list[tuple[str, int]] = []
    monkeypatch.setattr(
        integrity.ctypes, "windll",
        type("_Windll", (), {"kernel32": type("_Kernel32", (), {
            "SetFileAttributesW": staticmethod(lambda path, attrs: calls.append((path, attrs)) or 1),
        })()})(),
        raising=False,
    )

    monkeypatch.setattr(sys, "frozen", False, raising=False)
    integrity.write_manifest(root)
    assert calls == []

    monkeypatch.setattr(sys, "frozen", True, raising=False)
    integrity.write_manifest(root)
    assert len(calls) == 1
    assert calls[0][0] == str(integrity.manifest_path(root))
    assert calls[0][1] == integrity._HIDE_ATTRS


def test_the_file_list_is_capped(tmp_path: Path):
    """The banner names a few files and counts the rest - shipping hundreds of
    names over the bridge to be truncated in CSS helps nobody."""
    root = _tree(tmp_path)
    integrity.write_manifest(root)
    for i in range(30):
        (root / "zapret" / "strategies" / f"Extra{i}.bat").write_text("@echo off\n")

    report = integrity.verify(root)

    assert report.total == 30
    assert len(report.as_dict()["added"]) <= 20
