"""Notice when BridgeBox's own files stop matching what it shipped with.

Replaces the ACL hardening that used to live in install_security.py. The
finding behind it is unchanged and still true: the install folder inherits
`Authenticated Users: Modify` from the volume root, so anyone with a local
account can edit the files this app then executes as Administrator.

The chosen answer is now detection rather than prevention - the folder stays
writable, and the app says so loudly when anything in it changes.

WHAT THIS DOES AND DOES NOT BUY, stated plainly because it decides how much to
trust the banner: the manifest sits in the same writable folder as the files it
covers. Somebody who can replace a strategy .bat can replace baseline.json in
the same breath, and the banner will never fire. So this catches accidents, a
half-finished update, a file a user edited and forgot, and tampering by
anything that did not think to cover its tracks. It is not a defence against an
attacker who did.

Trust-on-first-use for a source checkout: the baseline is recorded the first
time BridgeBox runs without one, so changes made before that first run are
baked in as "original". A portable build closes that gap - see
tools/build_portable.py, which calls write_manifest() against the fully
assembled release folder as its last content-generation step, so the shipped
baseline.json already reflects exactly what a tamperer would have to change.
"""
from __future__ import annotations

import hashlib
import json
import logging
import sys
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)

MANIFEST_NAME = "baseline.json"
MANIFEST_VERSION = 1

# Zapret's own files are watched the same way whichever kind of install this
# is - the portable exe and a source checkout both keep a real, loose zapret/
# folder beside them (see tools/build_portable.py's release layout).
_ZAPRET_GLOBS = (
    "zapret/*.exe",
    "zapret/*.dll",
    "zapret/*.sys",
    "zapret/*.bin",
    "zapret/strategies/*.bat",
    "zapret/lists/*.txt",
)

# What is covered: everything that steers execution. A change to any of these
# is a change to what runs on this machine as Administrator.
#
# A portable build's own code and UI are not loose files any more -
# launcher.py, backend/bridgebox/**/*.py and frontend/dist/**/* are all
# baked into one bridgebox.exe (see tools/build_portable.py) - so a manifest
# built from the source-checkout globs against that tree would watch nothing
# real and "verify" a folder it never actually looked at. Watching the exe
# itself instead covers the same ground as one file, and covers it more
# strictly: it can't be tampered with one loose .py at a time.
WATCHED_GLOBS = (
    ("bridgebox.exe",) + _ZAPRET_GLOBS
    if getattr(sys, "frozen", False)
    else ("launcher.py", "run.bat") + _ZAPRET_GLOBS + (
        "backend/bridgebox/**/*.py",
        # The UI is covered too: a tampered bundle can show a running bridge
        # that is not running, or a green certificate that was never installed.
        "frontend/dist/**/*",
    )
)

# Deliberately NOT covered - these change during normal use, and a banner that
# fires on every launch is a banner nobody reads.
#   config.yaml            every settings change
#   logs/, temp/, certs/   written constantly; certs hold generated key material
#   ver.installed.txt      restamped by the updater
#   __pycache__            regenerated by the interpreter
IGNORED_PARTS = frozenset({"__pycache__", ".venv", "node_modules", ".git"})

# One read of every watched file. A few hundred small files plus winws.exe;
# measured in tens of milliseconds, but it still runs off the UI thread because
# a slow disk is not this code's decision to make.
_CHUNK = 1024 * 1024


def _is_ignored(relative: Path) -> bool:
    return any(part in IGNORED_PARTS for part in relative.parts)


def _digest(path: Path) -> str:
    sha = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(_CHUNK):
            sha.update(chunk)
    return sha.hexdigest()


def watched_files(root: Path) -> list[Path]:
    """Every file the manifest covers, relative to `root`, sorted.

    Sorted so two runs on the same tree produce byte-identical manifests -
    a manifest that reorders itself is one that looks changed when it is not."""
    root = Path(root)
    found: set[Path] = set()
    for pattern in WATCHED_GLOBS:
        for path in root.glob(pattern):
            if not path.is_file():
                continue
            relative = path.relative_to(root)
            if not _is_ignored(relative):
                found.add(relative)
    return sorted(found)


def build_manifest(root: Path) -> dict:
    root = Path(root)
    files = {}
    for relative in watched_files(root):
        try:
            files[relative.as_posix()] = _digest(root / relative)
        except OSError as exc:
            # A file we cannot read is not a file we can vouch for, but it is
            # also not worth refusing to start over.
            logger.warning("could not hash %s: %s", relative, exc)
    return {"version": MANIFEST_VERSION, "files": files}


@dataclass(frozen=True)
class IntegrityReport:
    """What changed since the baseline was taken.

    `verified` is False whenever the answer is not "everything matches",
    including when it could not be determined - the same safe direction
    strategy_adapt's stamp check errs in."""

    verified: bool
    # No baseline on disk yet, so there is nothing to compare against. Not a
    # warning: it is the state of a fresh install for the instant before the
    # baseline is written.
    baseline_missing: bool = False
    changed: list[str] = field(default_factory=list)
    missing: list[str] = field(default_factory=list)
    added: list[str] = field(default_factory=list)
    error: str | None = None

    @property
    def total(self) -> int:
        return len(self.changed) + len(self.missing) + len(self.added)

    def as_dict(self) -> dict:
        return {
            "verified": self.verified,
            "baselineMissing": self.baseline_missing,
            # Capped: the banner names a few files and counts the rest. A
            # frontend build changes hundreds at once, and shipping all of them
            # over the bridge to be truncated in CSS helps nobody.
            "changed": self.changed[:20],
            "missing": self.missing[:20],
            "added": self.added[:20],
            "total": self.total,
            "error": self.error,
        }


def manifest_path(root: Path) -> Path:
    return Path(root) / MANIFEST_NAME


def read_manifest(root: Path) -> dict | None:
    path = manifest_path(root)
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("could not read %s: %s", path, exc)
        return None
    if not isinstance(data, dict) or not isinstance(data.get("files"), dict):
        logger.warning("%s is not a manifest", path)
        return None
    return data


def write_manifest(root: Path) -> bool:
    """Record the current state as the baseline. Never raises."""
    root = Path(root)
    try:
        manifest = build_manifest(root)
        path = manifest_path(root)
        # Same write-then-rename every other file in this app uses, so a crash
        # mid-write cannot leave a truncated manifest that reads as "everything
        # changed".
        tmp = path.with_suffix(".tmp")
        tmp.write_text(json.dumps(manifest, ensure_ascii=False, indent=1), encoding="utf-8")
        tmp.replace(path)
    except OSError as exc:
        logger.error("could not write the integrity baseline: %s", exc)
        return False
    logger.info("integrity baseline recorded: %d files", len(manifest["files"]))
    return True


def verify(root: Path) -> IntegrityReport:
    """Compare the tree against the baseline. Never raises."""
    root = Path(root)
    try:
        baseline = read_manifest(root)
        if baseline is None:
            return IntegrityReport(verified=False, baseline_missing=True)

        recorded: dict[str, str] = baseline["files"]
        current = build_manifest(root)["files"]

        changed = sorted(
            name for name, digest in recorded.items()
            if name in current and current[name] != digest
        )
        missing = sorted(name for name in recorded if name not in current)
        added = sorted(name for name in current if name not in recorded)
    except Exception as exc:  # noqa: BLE001 - a diagnostic must not take the app down
        logger.exception("integrity check failed")
        return IntegrityReport(verified=False, error=str(exc))

    report = IntegrityReport(
        verified=not (changed or missing or added),
        changed=changed,
        missing=missing,
        added=added,
    )
    if not report.verified:
        logger.warning(
            "integrity: %d changed, %d missing, %d added (first: %s)",
            len(changed), len(missing), len(added),
            (changed + missing + added)[0],
        )
    return report


def ensure_baseline(root: Path) -> IntegrityReport:
    """Verify, recording a baseline first if there is none.

    The trust-on-first-use step. Called once at startup; the report it returns
    is what the banner reads."""
    report = verify(root)
    if report.baseline_missing:
        write_manifest(root)
        # Deliberately reported as verified rather than re-hashing: the
        # baseline was just taken FROM this tree, so a second pass can only
        # ever agree, and the extra read is pure cost.
        return IntegrityReport(verified=True)
    return report
