"""Build a portable, single-.exe BridgeBox release.

    python tools/build_portable.py
    python tools/build_portable.py --skip-frontend-build   # reuse frontend/dist
    python tools/build_portable.py --icon path\\to\\real.ico

Produces dist/BridgeBox_Portable/:

    bridgebox.exe   config.yaml   README.md   LICENSE.md   CREDITS.md
    baseline.json   certs/   temp/   logs/   zapret/

Every one of those, `bridgebox.exe` included, lives beside every other one -
no installer, no %APPDATA%, no registry key. That constraint is what decides
most of the shape below:

- backend/bridgebox/paths.py resolves config.yaml/logs/certs/temp/zapret
  against `sys.executable`'s own folder when frozen, so wherever this
  release folder gets copied to IS the install. See that module for the
  other half (frontend/dist has to come from somewhere ELSE - the exe
  itself - since it isn't shipped as a loose folder at all here).
- frontend/dist and backend/pyproject.toml are bundled INSIDE the exe
  (PyInstaller --add-data), not shipped loose, which is why the release
  folder above has no frontend/ entry.
- zapret/ ships loose and real: winws.exe is executed as a child process
  from wherever it sits on disk, and the strategy .bat/hostlist files are
  meant to stay user-editable.

Windows only, and it has to run through the SAME interpreter the backend's
tests do (backend/.venv) - PyInstaller has to import bridgebox to analyse
it, and pywebview/pythonnet/cryptography's own compiled extensions have to
come from the environment that actually has them installed.

stdlib plus PyInstaller and Pillow (both build-only - see pyproject.toml's
`[project.optional-dependencies].build`, never installed for a normal run).
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = REPO_ROOT / "backend"
FRONTEND_DIR = REPO_ROOT / "frontend"
ZAPRET_DIR = REPO_ROOT / "zapret"
VENV_PYTHON = BACKEND_DIR / ".venv" / "Scripts" / "python.exe"

BUILD_DIR = REPO_ROOT / "build" / "portable"  # PyInstaller's own work/spec/icon scratch space
PYI_DIST_DIR = BUILD_DIR / "dist"  # where PyInstaller drops the built exe
RELEASE_DIR = REPO_ROOT / "dist" / "BridgeBox_Portable"

APP_NAME = "bridgebox"
PRODUCT_NAME = "BridgeBox"
COMPANY_NAME = "BridgeBox"
FILE_DESCRIPTION = "BridgeBox Desktop Client"

# The wordmark's own light-theme colour (tokens.css --navy-600 / --color-accent) -
# so a generated placeholder icon still reads as unmistakably "this app",
# not a random PyInstaller default.
BRAND_COLOR = (0x1D, 0x4E, 0xD8)

_VERSION_RE = re.compile(r'^\s*version\s*=\s*"([^"]+)"', re.MULTILINE)
_VERSION_PART_RE = re.compile(r"\d+")
_PRERELEASE_RE = re.compile(r"(?:a|b|rc)(\d+)$")


def log(message: str) -> None:
    print(f"[build] {message}", flush=True)


def run(cmd: list[str], *, cwd: Path | None = None) -> None:
    log("  $ " + " ".join(str(part) for part in cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


# ---- version -----------------------------------------------------------


def read_version() -> str:
    """The one place BridgeBox's version is written by hand - same file
    version.py reads at runtime, so packaging can never drift from it."""
    text = (BACKEND_DIR / "pyproject.toml").read_text(encoding="utf-8")
    match = _VERSION_RE.search(text)
    if not match:
        raise SystemExit("could not find `version = \"...\"` in backend/pyproject.toml")
    return match.group(1)


def version_tuple(version_string: str) -> tuple[int, int, int, int]:
    """PEP 440 "0.1.0b1" -> the four plain integers a Windows PE version
    resource needs (FILEVERSION/PRODUCTVERSION cannot hold letters).

    The pre-release number becomes the 4th component - "0.1.0b1" and
    "0.1.0b2" get FILEVERSION 0.1.0.1 and 0.1.0.2, not the same 0.1.0.0
    twice, so Explorer's Details tab can still tell two betas apart. A
    final release (no a/b/rc suffix) gets 0 there."""
    prerelease = _PRERELEASE_RE.search(version_string)
    core = version_string[: prerelease.start()] if prerelease else version_string
    parts = [int(part) for part in _VERSION_PART_RE.findall(core)]
    parts = (parts + [0, 0, 0])[:3]
    build = int(prerelease.group(1)) if prerelease else 0
    return (parts[0], parts[1], parts[2], build)


def write_version_info(version: str, out_path: Path) -> None:
    """PyInstaller's --version-file format: a Python literal it evals
    itself (see PyInstaller.utils.win32.versioninfo), not arbitrary text -
    the structure below is that module's own documented shape, not
    something invented here."""
    filevers = version_tuple(version)
    year = datetime.now().year
    content = f"""# UTF-8
#
# Generated by tools/build_portable.py - do not edit by hand, it is
# overwritten on every build. Edit backend/pyproject.toml's version instead.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers!r},
    prodvers={filevers!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [StringStruct(u'CompanyName', u'{COMPANY_NAME}'),
           StringStruct(u'FileDescription', u'{FILE_DESCRIPTION}'),
           StringStruct(u'FileVersion', u'{version}'),
           StringStruct(u'InternalName', u'{APP_NAME}'),
           StringStruct(u'LegalCopyright', u'Copyright (c) {year} {COMPANY_NAME} contributors'),
           StringStruct(u'OriginalFilename', u'{APP_NAME}.exe'),
           StringStruct(u'ProductName', u'{PRODUCT_NAME}'),
           StringStruct(u'ProductVersion', u'{version}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""
    out_path.write_text(content, encoding="utf-8")


# ---- icon ----------------------------------------------------------------


def ensure_icon(icon_arg: str | None) -> Path:
    """A real designed .ico, if one was passed in - otherwise a generated
    placeholder (brand-navy rounded square, "bb" monogram matching the
    collapsed sidebar's own identity in BrandLogo.tsx), so the exe never
    ships with PyInstaller's generic default icon. Swap in real artwork
    later with --icon; nothing else about the build changes."""
    if icon_arg:
        path = Path(icon_arg)
        if not path.exists():
            raise SystemExit(f"--icon {path} does not exist")
        return path

    path = BUILD_DIR / "bridgebox.ico"
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    if path.exists():
        return path

    log("No --icon given - generating a placeholder .ico (brand navy, \"bb\")")
    from PIL import Image, ImageDraw, ImageFont

    sizes = (16, 24, 32, 48, 64, 128, 256)
    font_path = Path(os.environ.get("WINDIR", r"C:\Windows")) / "Fonts" / "segoeuib.ttf"
    images = []
    for size in sizes:
        img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)
        draw.rounded_rectangle(
            (0, 0, size - 1, size - 1), radius=round(size * 0.22), fill=(*BRAND_COLOR, 255)
        )
        try:
            font = ImageFont.truetype(str(font_path), round(size * 0.5))
        except OSError:
            font = ImageFont.load_default()
        text = "bb"
        left, top, right, bottom = draw.textbbox((0, 0), text, font=font)
        tw, th = right - left, bottom - top
        draw.text(
            ((size - tw) / 2 - left, (size - th) / 2 - top), text, font=font, fill="white"
        )
        images.append(img)

    images[-1].save(path, format="ICO", sizes=[(s, s) for s in sizes], append_images=images[:-1])
    return path


# ---- frontend / dependencies ----------------------------------------------


def build_frontend(*, skip: bool) -> None:
    dist_index = FRONTEND_DIR / "dist" / "index.html"
    if skip:
        if not dist_index.exists():
            raise SystemExit("--skip-frontend-build given but frontend/dist/index.html is missing")
        log("Skipping frontend build (--skip-frontend-build) - reusing frontend/dist as-is")
        return

    npm = shutil.which("npm")
    if not npm:
        raise SystemExit("npm not found on PATH - install Node.js 18+")

    log("Building frontend (npm run build)...")
    if not (FRONTEND_DIR / "node_modules").exists():
        run([npm, "install"], cwd=FRONTEND_DIR)
    run([npm, "run", "build"], cwd=FRONTEND_DIR)

    if not dist_index.exists():
        raise SystemExit(f"frontend build did not produce {dist_index}")


def ensure_build_deps() -> None:
    if not VENV_PYTHON.exists():
        raise SystemExit(
            f"{VENV_PYTHON} does not exist - run run.bat once first to create the backend venv"
        )
    log("Checking build dependencies (PyInstaller, Pillow)...")
    check = subprocess.run(
        [str(VENV_PYTHON), "-c", "import PyInstaller, PIL"], capture_output=True
    )
    if check.returncode != 0:
        run(
            [
                str(VENV_PYTHON),
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "-q",
                "-e",
                f"{BACKEND_DIR}[build]",
            ]
        )


# ---- clean -----------------------------------------------------------------


def clean_previous_build() -> None:
    for path in (BUILD_DIR, RELEASE_DIR):
        if path.exists():
            log(f"Removing previous build output: {path}")
            shutil.rmtree(path)


# ---- PyInstaller -------------------------------------------------------


def run_pyinstaller(icon_path: Path, version_info_path: Path) -> Path:
    log("Compiling bridgebox.exe (PyInstaller)...")
    cmd = [
        str(VENV_PYTHON),
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--onefile",
        # No console window ever, on a double-click launch (aliases:
        # --noconsole / -w). See paths.py/logging_setup.py for why the app
        # is safe to run with sys.stdout/sys.stderr as None either way.
        "--windowed",
        # Embeds <requestedExecutionLevel level="requireAdministrator">, so
        # Windows itself prompts for elevation on launch - the portable exe
        # has no run.bat wrapper to do that with a PowerShell relaunch.
        "--uac-admin",
        "--name",
        APP_NAME,
        "--icon",
        str(icon_path),
        "--version-file",
        str(version_info_path),
        "--paths",
        str(BACKEND_DIR),
        # Bundled read-only resources - see paths.py's RESOURCE_ROOT and
        # version.py's frozen _from_pyproject(). Kept at the SAME relative
        # path ("frontend/dist/...") both frozen and from source, so
        # nothing downstream needs to know which mode it's running in.
        "--add-data",
        f"{FRONTEND_DIR / 'dist'}{os.pathsep}frontend/dist",
        "--add-data",
        f"{BACKEND_DIR / 'pyproject.toml'}{os.pathsep}.",
        # launcher.py only imports bridgebox.desktop from inside a function,
        # and desktop.py reaches the rest of the package through it - belt
        # and suspenders against PyInstaller's analysis missing a branch.
        "--hidden-import",
        "bridgebox.desktop",
        "--collect-submodules",
        "bridgebox",
        "--exclude-module",
        "pytest",
        "--exclude-module",
        "pytest_asyncio",
        "--distpath",
        str(PYI_DIST_DIR),
        "--workpath",
        str(BUILD_DIR / "work"),
        "--specpath",
        str(BUILD_DIR),
        str(REPO_ROOT / "launcher.py"),
    ]
    run(cmd)

    exe = PYI_DIST_DIR / f"{APP_NAME}.exe"
    if not exe.exists():
        raise SystemExit(f"PyInstaller reported success but {exe} does not exist")
    return exe


# ---- release assembly -----------------------------------------------------

_ZAPRET_IGNORE = {"__pycache__", "originalstrategies", ".git"}


def _ignore_zapret_cruft(_directory: str, names: list[str]) -> set[str]:
    return {name for name in names if name in _ZAPRET_IGNORE}


def write_default_config(config_path: Path) -> None:
    """A clean config.yaml, generated from the real Config model rather than
    hand-duplicated YAML - byte-for-byte what save_config() would write for
    an all-defaults install, so there is exactly one place that shape
    is defined. Runs in its own interpreter so this script's own process
    never imports bridgebox with the wrong sys.frozen state (see
    write_integrity_baseline below, which needs the opposite)."""
    script = (
        "import sys; sys.path.insert(0, r'{backend}'); "
        "from bridgebox.config import Config, save_config; "
        "save_config(Config(), r'{path}')"
    ).format(backend=BACKEND_DIR, path=config_path)
    run([str(VENV_PYTHON), "-c", script])


def assemble_release(exe_path: Path) -> None:
    log(f"Assembling release folder: {RELEASE_DIR}")
    RELEASE_DIR.mkdir(parents=True)
    shutil.copy2(exe_path, RELEASE_DIR / f"{APP_NAME}.exe")

    for name in ("certs", "temp", "logs"):
        (RELEASE_DIR / name).mkdir()

    shutil.copytree(ZAPRET_DIR, RELEASE_DIR / "zapret", ignore=_ignore_zapret_cruft)

    for filename in ("README.md", "LICENSE.md", "CREDITS.md"):
        src = REPO_ROOT / filename
        if src.exists():
            shutil.copy2(src, RELEASE_DIR / filename)
        else:
            log(f"  warning: {filename} not found at repo root - release will ship without it")

    write_default_config(RELEASE_DIR / "config.yaml")


def write_integrity_baseline(release_dir: Path) -> None:
    """The trust-on-first-use gap integrity.py's own docstring names: run
    from a subprocess with sys.frozen forced True, so WATCHED_GLOBS picks
    its frozen branch (bridgebox.exe + zapret/, not the source-tree globs a
    portable release doesn't have) and the manifest this writes matches
    what the packaged app will actually check itself against at runtime."""
    script = (
        "import sys; sys.frozen = True; sys.path.insert(0, r'{backend}'); "
        "from bridgebox import integrity; "
        "ok = integrity.write_manifest(r'{root}'); "
        "sys.exit(0 if ok else 1)"
    ).format(backend=BACKEND_DIR, root=release_dir)
    run([str(VENV_PYTHON), "-c", script])


# ---- validation -----------------------------------------------------------

_REQUIRED_ENTRIES = (
    "bridgebox.exe",
    "config.yaml",
    "README.md",
    "LICENSE.md",
    "CREDITS.md",
    "certs",
    "temp",
    "logs",
    "zapret",
    "baseline.json",
)


def _integrity_check_output(release_dir: Path) -> tuple[bool, str]:
    script = (
        "import sys; sys.frozen = True; sys.path.insert(0, r'{backend}'); "
        "from bridgebox import integrity; "
        "report = integrity.verify(r'{root}'); "
        "print(report.as_dict()); "
        "sys.exit(0 if report.verified else 1)"
    ).format(backend=BACKEND_DIR, root=release_dir)
    result = subprocess.run(
        [str(VENV_PYTHON), "-c", script], capture_output=True, text=True
    )
    return result.returncode == 0, (result.stdout.strip() or result.stderr.strip())


def validate_release() -> None:
    log("Validating the release...")
    problems: list[str] = []

    for name in _REQUIRED_ENTRIES:
        if not (RELEASE_DIR / name).exists():
            problems.append(f"missing {name}")

    exe = RELEASE_DIR / f"{APP_NAME}.exe"
    if exe.exists():
        size_mb = exe.stat().st_size / (1024 * 1024)
        log(f"  {APP_NAME}.exe: {size_mb:.1f} MB")
        if size_mb < 5:
            problems.append(
                f"{APP_NAME}.exe is only {size_mb:.1f} MB - looks too small for a "
                "webview+aiohttp+cryptography build, the compile may have failed silently"
            )

        # Best-effort only: this catches the build machine's own path
        # showing up as plain, uncompressed text (a PyInstaller warning
        # file or a bundled resource copied verbatim) - it cannot see
        # inside the compressed PYZ archive the actual bytecode lives in,
        # so a clean result here is evidence, not a proof of nothing leaked.
        needle = str(REPO_ROOT).encode("utf-8")
        if needle in exe.read_bytes():
            problems.append(f"the build machine's own path ({REPO_ROOT}) is embedded in {exe.name}")

    if (RELEASE_DIR / "baseline.json").exists():
        verified, detail = _integrity_check_output(RELEASE_DIR)
        if not verified:
            problems.append(f"integrity baseline does not verify against its own tree: {detail}")

    if problems:
        for problem in problems:
            log(f"  PROBLEM: {problem}")
        raise SystemExit(f"{len(problems)} validation problem(s) - see above")

    log(f"  OK - {len(_REQUIRED_ENTRIES)} required entries present, integrity baseline verifies")


# ---- entry point ------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--skip-frontend-build",
        action="store_true",
        help="Reuse the existing frontend/dist instead of running npm run build again.",
    )
    parser.add_argument(
        "--icon",
        help="Path to a real .ico to embed. Without this, a generated placeholder is used.",
    )
    return parser.parse_args()


def main() -> None:
    if sys.platform != "win32":
        raise SystemExit("This builds a Windows .exe and only runs on Windows.")

    args = parse_args()
    version = read_version()
    log(f"BridgeBox {version}")

    ensure_build_deps()
    build_frontend(skip=args.skip_frontend_build)
    clean_previous_build()
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    icon_path = ensure_icon(args.icon)
    version_info_path = BUILD_DIR / "version_info.txt"
    write_version_info(version, version_info_path)

    exe_path = run_pyinstaller(icon_path, version_info_path)
    assemble_release(exe_path)
    write_integrity_baseline(RELEASE_DIR)
    validate_release()

    log("")
    log(f"Done: {RELEASE_DIR}")


if __name__ == "__main__":
    main()
